### ISSUE TITLE
Ready for 2.0?

### ISSUE THREAD

**Issue by DuoDex** [DuoDex/CrowdSourcedScience#20]
It seems we have science for each and every biome. Should I do a cleanup, add a few science reports here and there and then release a v2.0?

Help will be appreciated - I'm aiming for 3 science reports for each situation at the moment. I also kinda want to change the name to Expanded Science Reports - Crowd Edition or something that makes it a bit more obvious that we have support for the 0.90 biomes.

**Comment by chaltak** [comment]
Sounds like a good plan to me. What help would you be looking for, besides adding more reports?

**Comment by madsailor** [comment]
New release and new name are both great ideas IMO. Maybe 'Community' instead of 'Crowd' edition to emphasize the collective nature?  One full round of Kerbin reports was enough for me personally, though 3 sets (or really the-more-the-better) is a great goal to aim for for the project. I plan on working on complete sets for at least the rest of Kerbins' SOI and moving from there as time permits, likely after v2.0.

**Comment by harryyoung** [comment]
I think we can go for it.
As for the name: Science Reports - Community Edition works for me, however I prefer the old name.

**Comment by Olympic1** [comment]
Great idea, but for the moment I can't help writing new reports because I'm updating LTech and also helping with KittopiaTech. Will help after those two mods are ready.

For the name, I prefer the old name.

**Comment by madsailor** [comment]
Just had an idea. Before v2.0 we should leverage the reports we already have for biome support by moving them from 'default' to appropriate biomes. This should give us much better biome support for bodies outside of Kerbin.  Will work on it today.

**Comment by DuoDex** [comment]
Thank you all!

**Comment by Olympic1** [comment]
Now that I have some more time, I'll do some more reports for the USI support.

**Comment by madsailor** [comment]
Ok, now I definitely vote for a new release. Since the last version we have:  

* Added a complete set of (vanilla) Kerbin reports
* Added a complete set of (vanilla) Mun reports
* Added a complete set of SCANSat reports that went upstream
* Moved HUGE numbers of reports over for biome support
* Implemented support for 5 more mods
* Probably a bunch of other stuff I'm forgetting  

People that come here to the repo will have the latest updates, but the CKAN folks are missing out on all the new content.

**Comment by harryyoung** [comment]
I second

**Comment by Olympic1** [comment]
Agreed, I'll add my USI support in after 2.0

**Comment by Olympic1** [comment]
It's been quiet for almost 2 weeks

**Comment by DuoDex** [comment]
So it has.

**Comment by harryyoung** [comment]
I think we were all kinda waiting for someone to flick the switch on the release and update CKAN and the forum post.

**Comment by madsailor** [comment]
Second that. DD, as maintainer, should be go/no go on releases.  The next release has been setup by collaboration of us all (Olympic1, harryyoung and myself).  Duo Dex, it's up to you to make changes or pull the trigger for a new release.

**Comment by DuoDex** [comment]
Bad me.

Go ahead and pull the trigger on new release, I'm on mobile and can't download stuffs/edit CKAN

I'll edit the forum post though.

**Comment by Olympic1** [comment]
v2.0 is released
