### ISSUE TITLE
PresMat Barometer Can't be used with Vaccum

### ISSUE THREAD

**Issue by bigorangemachine** [DuoDex/CrowdSourcedScience#40]
I installed CSS and right away the PresMat Barometer (stock Atmospheric Pressure Scan) can't be [done in a vacuum](http://wiki.kerbalspaceprogram.com/wiki/Science#Possible_combinations_of_Activity.2C_Situation.2C_and_Biome).  In 1.0 this is allowed.  For whatever reason CSS reverts this experiment to the 0.90 settings.

I suspect other experiments need updating.

**Comment by madsailor** [comment]
I was able to get a report from vacuum with the Barometer using KSP 1.0.2 and the latest CSS as you can see here: https://i.imgur.com/gBHzehq.png.  CSS does not remove ANY reports/functionality from stock; it only adds reports.  I suspect that it is another mod that is conflicting for you.

**Comment by bigorangemachine** [comment]
Hey madsailor,
Removing CSS fixed this issue.

I downloaded from Releases page here on github.

**Comment by madsailor** [comment]
This may need to stay in the limbo stage until someone else can confirm this issue, since I cannot recreate it myself.  I will be away for a bit and unable to follow up on this, but if you leave a detailed list of the mods that you have installed perhaps it will be helpful to others who find themselves here.  Also, I would recommend the standard procedure of uninstalling everything, reinstalling vanilla KSP, then adding your mods (starting with CSS) 1 by 1 until you run into an issue again.

**Comment by bigorangemachine** [comment]
Hey Madsailor,

I have the mods:

* Kerbal Alarm Clock
* Transfer Window Planner
* Trajectories
* Stage Recovery
* Muffler
* Precise Node
* Kerbal Engineer Redux
* Flight Manager

None of these mess with the science.  I'm honestly thinking its a setting in mod manager
